//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Color
    {
        public int ColorID { get; set; }
        public string ColorName { get; set; }
        public string ColorHash { get; set; }
        public string ColorDescription { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
