//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public System.DateTime OderDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> RequirdDate { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public byte[] OrderTimeStamp { get; set; }
        public string TransactionStatus { get; set; }
        public string Error { get; set; }
        public string FullFilled { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public string Paid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    }
}
