//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderDetailID { get; set; }
        public string OrderGuid { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> GrossPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    }
}
