//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductGUID { get; set; }
        public string SKU { get; set; }
        public string ProductName { get; set; }
        public string ProductShortDesc { get; set; }
        public string ProductLongDesc { get; set; }
        public Nullable<int> QuantityPerUnit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string UnitWeight { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<bool> Available { get; set; }
        public string Picture { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Featured { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
