//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatedProduct
    {
        public int RelatedProductsID { get; set; }
        public string Product { get; set; }
        public string RelatedProduct1 { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
